"""Add performance indexes

Revision ID: 03e66235b593
Revises: 27d1e20b3003
Create Date: 2026-01-21 05:21:53.261898

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "03e66235b593"
down_revision: Union[str, Sequence[str], None] = "27d1e20b3003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_members", schema=None) as batch_op:
        batch_op.create_index("ix_member_group_id", ["group_id"], unique=False)

    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.create_index("ix_record_group_id", ["group_id"], unique=False)
        batch_op.create_index(
            "ix_record_group_timestamp", ["group_id", "timestamp"], unique=False
        )
        batch_op.create_index("ix_record_timestamp", ["timestamp"], unique=False)

    with op.batch_alter_table("attendance_sessions", schema=None) as batch_op:
        batch_op.create_index("ix_session_date", ["date"], unique=False)
        batch_op.create_index(
            "ix_session_group_date", ["group_id", "date"], unique=False
        )
        batch_op.create_index("ix_session_group_id", ["group_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_session_group_id")
        batch_op.drop_index("ix_session_group_date")
        batch_op.drop_index("ix_session_date")

    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.drop_index("ix_record_timestamp")
        batch_op.drop_index("ix_record_group_timestamp")
        batch_op.drop_index("ix_record_group_id")

    with op.batch_alter_table("attendance_members", schema=None) as batch_op:
        batch_op.drop_index("ix_member_group_id")

    # ### end Alembic commands ###
